export const GET_EMPLOYEES_START = "GET_EMPLOYEES_START";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_FAIL = "GET_EMPLOYEES_FAIL";

export const INIT_EMPLOYEE  = "INIT_EMPLOYEE";
export const TOGGLE = "TOGGLE"
export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"